export type SoundId = keyof typeof sounds;

export const sounds = {
  song_1: {
    title: "The Inner Core",
    mp3: "1_The_Inner_Core.mp3",
    tags: ["deep", "technology", "alien", "computers", "reactor"],
  },
  song_2: {
    title: "Bubbling Pools",
    mp3: "2_Bubbling_Pools.mp3",
    tags: ["bubbles", "music", "ethereal", "mystical", "sand", "magic", "Alchemists"],
    disabled: true,
  },
  song_3: {
    title: "March of the Faithful",
    mp3: "3_The_March_of_the_Faithful.mp3",
    tags: ["music", "brooding", "dark", "sad", "suspense", "drums", "abstract"],
  },
  song_4: {
    title: "Solemn Vow",
    mp3: "4_Solemn_Vow-a.mp3",
    tags: ["brooding", "sad", "brave", "uplifting"],
  },
  song_5: {
    title: "Desert Bazaar",
    mp3: "5_Desert_Bazaar.mp3",
    tags: ["arabian", "dune", "market", "suspense", "alien", "magic", "Voyages of Marco Polo"],
  },
  song_6: {
    title: "Abyssal Gaze",
    mp3: "6_Abyssal_Gaze.mp3",
    tags: ["dark", "void", "lonely"],
    disabled: true,
  },
  song_7: {
    title: "The Desert Awaits",
    mp3: "7_The_Desert_Awaits.mp3",
    tags: ["sand", "ethnic", "tribal", "wind", "Forbidden Desert"],
    disabled: true,
  },
  song_8: {
    title: "Dust to Dust",
    mp3: "8_New_Dust_to_Dust.mp3",
    tags: ["ethereal", "deep", "brooding", "abstract", "music"],
  },
  song_9: {
    title: "Before the Storm",
    mp3: "9_Before_The_Storm.mp3",
    tags: ["calm", "rain", "mourning"],
  },
  song_10: {
    title: "In the Shadows",
    mp3: "10_In_The_Shadows.mp3",
    tags: ["abstract", "void", "wind", "music"],
  },
  song_11: {
    title: "Shelter from the Storm",
    mp3: "11_Shelter_from_the_Storm.mp3",
    tags: ["brooding", "abstract", "music", "menacing", "whispers", "strange", "ethereal"],
    disabled: true,
  },
  song_12: {
    title: "Disembodied Spirits",
    mp3: "12_Disembodied_Spirits.mp3",
    tags: ["ghosts", "dark", "abstract", "music", "ethereal", "menacing", "strange", "sarcophagus"],
  },
  song_13: {
    title: "Cave of Time",
    mp3: "13_Cave_of_Time.mp3",
    tags: ["dripping", "bats", "underground", "wind", "dungeon", "music", "suspense"],
    disabled: true,
  },
  song_14: {
    title: "Protean Fields",
    mp3: "14_Protean_Fields.mp3",
    tags: ["suspense", "ethereal", "astral", "drone"],
  },
  song_15: {
    title: "Alien Machine Shop",
    mp3: "15_Alien_Machine_Shop.mp3",
    tags: ["spaceship", "repair", "mechanic"],
    disabled: true,
  },
  song_16: {
    title: "Busy Space Port",
    mp3: "16_Busy_Space_Port.mp3",
    tags: ["spaceship", "travel", "alien", "outpost", "spacestation", "Among the Stars", "space station"],
    disabled: true,
  },
  song_17: {
    title: "Alien Night Club",
    mp3: "17_Alien_Night_Club.mp3",
    tags: ["cantina", "bar", "music", "scum", "underworld", "star wars", "City of Remnants"],
    disabled: true,
  },
  song_18: {
    title: "House on the Hill",
    mp3: "18_House_on_the_Hill.mp3",
    tags: ["lovecraft", "betrayal", "creepy", "haunted", "abandoned", "ghosts", "Betrayal at House on the Hill", "vampire"],
  },
  song_19: {
    title: "Age of Sail",
    mp3: "19_Age_of_Sail.mp3",
    tags: ["ships", "ocean", "navy", "naval", "wind", "waves", "seven seas", "50 fathoms"],
    disabled: true,
  },
  song_20: {
    title: "Dark Continent",
    mp3: "20_Dark_Continent_aa.mp3",
    tags: ["rhythm", "drums", "chant", "tribal"],
  },
  song_21: {
    title: "Derelict Freighter",
    mp3: "21_Derelict_Freighter.mp3",
    tags: ["spaceship", "salvage", "space opera", "reavers", "Level 7", "Theseus", "Legendary Encounters"],
  },
  song_22: {
    title: "True West",
    mp3: "22_True_West_a.mp3",
    tags: ["horses", "western", "cowboys", "dusty", "town", "Carson City", "Bang", "Spurs"],
  },
  song_23: {
    title: "The Slaughtered Ox",
    mp3: "23_The_Slaughtered_Ox.mp3",
    tags: ["inn", "tavern", "hearth", "food", "drink"],
  },
  song_24: {
    title: "Forbidden Galaxy!",
    mp3: "24_Forbidden_Galaxy.mp3",
    tags: ["space", "weapons", "vintage", "planet", "Alien Frontiers"],
  },
  song_25: {
    title: "Deep Space EVA",
    mp3: "25_Deep_Space_EVA.mp3",
    tags: ["spacewalk", "asteroids"],
    disabled: true,
  },
  song_26: {
    title: "Uncommon Valor",
    mp3: "26_Uncommon_Valor_a.mp3",
    tags: ["war", "combat", "wwii", "wwi", "tanks", "infantry", "trenches", "Memoir 44", "Heroes of Normandie"],
  },
  song_27: {
    title: "Xingu Nights",
    mp3: "27_Xingu_Nights.mp3",
    tags: ["jungle", "birds", "insects", "trees", "forest", "Cacao", "Relic Runners"],
  },
  song_28: {
    title: "Nephilim Labs FE",
    mp3: "28_Nephilim_Labs_FE.mp3",
    tags: ["fragged empire", "laboratory", "genetics", "experiments", "Level 7", "Theseus", "Legendary Encounters"],
  },
  song_29: {
    title: "Kaltoran Craft FE",
    mp3: "29_Kaltoran_Craft_FE.mp3",
    tags: ["fragged empire", "spaceship", "starship", "space opera"],
    disabled: true,
  },
  song_30: {
    title: "Los Vangeles 3030",
    mp3: "30_Los_Vangeles_3030.mp3",
    tags: ["synthesizer", "blade runner", "future", "city", "urban", "City of Remnants", "cyberpunk"],
  },
  song_31: {
    title: "Frozen Wastes",
    mp3: "31_Frozen_Wastes.mp3",
    tags: ["ice", "arctic", "tundra", "wind", "snow", "cold", "Arctic Scavengers", "Dead of Winter"],
  },
  song_32: {
    title: "City and the City",
    mp3: "32_City_and_the_City.mp3",
    tags: ["urban", "streets", "traffic", "nightlife", "Police Precinct"],
  },
  song_33: {
    title: "Far Above the World",
    mp3: "33_Far_Above_the_World.mp3",
    tags: ["space", "outerspace", "quiet", "dark", "astronaut", "spacewalk"],
  },
  song_34: {
    title: "Clash of Kings",
    mp3: "34_Clash_of_Kings.mp3",
    tags: ["battle", "weapons", "armor", "marching", "army", "armies", "battlefield", "combat"],
  },
  song_35: {
    title: "Swamplandia",
    mp3: "35_Swamplandia.mp3",
    tags: ["swamp", "jungle", "insects", "water", "humid", "sticky"],
  },
  song_36: {
    title: "Down by the Sea",
    mp3: "36_Down_by_the_Sea.mp3",
    tags: ["water", "ocean", "beach", "gulls", "birds", "sand", "dunes", "surf", "wind", "breeze"],
  },
  song_37: {
    title: "Catacombs",
    mp3: "37_Catacombs.mp3",
    tags: ["underground", "dark", "grave", "tomb", "skeletons", "skulls", "burial", "sarcophagus"],
    disabled: true,
  },
  song_38: {
    title: "Into the Deep",
    mp3: "38_Into_the_Deep.mp3",
    tags: ["underwater", "water", "deep", "dive", "scuba", "darkness", "ocean floor", "diver", "drown", "Aquasphere"],
  },
  song_39: {
    title: "Temple of the Eye",
    mp3: "39_Temple_of_the_Eye.mp3",
    tags: ["cult", "chant", "ritual", "dark energy", "doomsday", "church"],
  },
  song_40: {
    title: "The Long Rain",
    mp3: "40_The_Long_Rain.mp3",
    tags: ["downpour", "storm", "monsoon", "water", "productivty"],
  },
  song_41: {
    title: "Starship Bridge",
    mp3: "41_Starship_Bridge.mp3",
    tags: ["deck", "space", "spaceship", "enterprise", "star trek", "Space Cadets"],
  },
  song_42: {
    title: "Rise of the Ancients",
    mp3: "42_Rise_of_the_Ancients.mp3",
    tags: ["cthulhu", "cult", "lovecraft", "demon", "monster", "Arkham", "Eldritch", "Elder Scrolls"],
  },
  song_43: {
    title: "Dome City Center",
    mp3: "43_Dome_City_Center.mp3",
    tags: ["urban", "future", "futuristic"],
  },
  song_44: {
    title: "Victorian London",
    mp3: "44_Victorian_London.mp3",
    tags: ["jack the ripper", "Sherlock Holmes", "city", "streets", "urban", "19th century"],
  },
  song_45: {
    title: "Samurai HQ",
    mp3: "45_Samurai_HQ.mp3",
    tags: ["horses", "japanese", "army", "bivouac", "camp", "feudalism", "warlords", "mongol", "asia", "asian", "Yedo", "Shogun"],
    disabled: true,
  },
  song_46: {
    title: "Cathedral",
    mp3: "46_Cathedral.mp3",
    tags: ["church", "holy", "paladin", "ethereal", "chant", "monks", "prayer", "temple"],
  },
  song_47: {
    title: "There be Dragons!",
    mp3: "47_There_be_Dragons.mp3",
    tags: ["fight", "battle", "dragons", "quest", "Dragon Rampage", "Dragon Run", "combat"],
  },
  song_48: {
    title: "Overland with Oxen",
    mp3: "48_Overland_with_Oxen.mp3",
    tags: ["ox", "cart", "wagon", "travel", "horses"],
  },
  song_49: {
    title: "Goblin's Cave",
    mp3: "49_Goblin's_Cave.mp3",
    tags: ["dark", "dripping", "stream", "cavern", "monsters", "kobolds"],
  },
  song_50: {
    title: "Super Hero!",
    mp3: "50_Super_Hero.mp3",
    tags: ["action", "city", "explosions", "thriller"],
    disabled: true,
  },
  song_51: {
    title: "Woodland Campsite",
    mp3: "51_Woodland_Campsite.mp3",
    tags: ["woods", "campfire", "fire", "horses", "forest"],
  },
  song_52: {
    title: "Warehouse 13",
    mp3: "52_Warehouse_13.mp3",
    tags: ["factory", "industrial", "abandoned"],
  },
  song_53: {
    title: "Strangers on a Train",
    mp3: "53_Strangers_on_a_Train.mp3",
    tags: ["orient express", "rail", "railroad", "mystery", "dining", "Ticket to Ride", "Mystery Express"],
    disabled: true,
  },
  song_54: {
    title: "Mountain Tavern",
    mp3: "54_Mountain_Tavern.mp3",
    tags: ["inn", "hearth", "food", "drink"],
  },
  song_55: {
    title: "Ice Cavern",
    mp3: "55_Ice_Cavern.mp3",
    tags: ["cave", "freezing", "cold", "snow", "echo", "frozen", "winter"],
  },
  song_56: {
    title: "Medieval Town",
    mp3: "56_Medieval_Town.mp3",
    tags: ["medieval", "town", "city", "Village"],
  },
  song_57: {
    title: "Colosseum",
    mp3: "57_Colosseum.mp3",
    tags: ["roman", "rome", "gladiators", "combat", "fight", "arena", "Spartacus"],
    disabled: true,
  },
  song_58: {
    title: "Terror",
    mp3: "58_Terror.mp3",
    tags: ["terror", "halloween", "scary"],
  },
  song_59: {
    title: "Dinotopia",
    mp3: "59_Dinotopia.mp3",
    tags: ["dinosaurs", "jungle", "Evolution", "Evo", "Triassic Terror", "Raptor"],
    disabled: true,
  },
  song_60: {
    title: "Dark and Stormy",
    mp3: "60_Dark_and_Stormy.mp3",
    tags: ["rain", "wind", "spooky", "weather", "Betrayal at House on the Hill", "sleeping", "vampire"],
  },
  song_61: {
    title: "Orbital Platform",
    mp3: "61_Orbital_Platform.mp3",
    tags: ["space", "future", "stars", "trek", "starfleet"],
  },
  song_62: {
    title: "Middle Earth:Dawn",
    mp3: "62_Middle_Earth_Dawn.mp3",
    tags: ["travel", "adventure", "peaceful", "tolkien", "birds", "breeze", "sleeping", "elves", "hobbits"],
    disabled: true,
  },
  song_63: {
    title: "Industrial Shipyard",
    mp3: "63_Industrial_Shipyard.mp3",
    tags: ["boats", "ships", "industry", "docks", "harbor", "freight", "cargo", "Shipyard"],
    disabled: true,
  },
  song_64: {
    title: "Mountain Pass",
    mp3: "64_Mountain_Pass.mp3",
    tags: ["journey", "travel", "wind", "rain", "snow", "horses"],
    disabled: true,
  },
  song_65: {
    title: "Dungeon I",
    mp3: "65_Dungeon_I.mp3",
    tags: ["adventure", "treasure", "underground", "quest"],
  },
  song_66: {
    title: "Royal Salon",
    mp3: "66_Royal_Salon.mp3",
    tags: ["party", "18th century", "france", "french", "whispers", "baroque", "classical", "wigs", "parlor", "court"],
    disabled: true,
  },
  song_67: {
    title: "Asylum",
    mp3: "67_Asylum.mp3",
    tags: ["insane", "crazy", "spooky", "madness", "bedlam", "arkham", "straight jackets", "T.I.M.E. Stories", "TIME Stories"],
  },
  song_68: {
    title: "1940's Office",
    mp3: "68_1940s_Office.mp3",
    tags: ["40s", "50s", "30s", "gangster", "mobster", "bogart", "vintage", "1940s", "1930s"],
  },
  song_69: {
    title: "Forest: Night",
    mp3: "69_Forest_Night.mp3",
    tags: ["quiet", "breeze", "trees", "birds", "wind", "sleeping"],
  },
  song_70: {
    title: "The Age of Steam",
    mp3: "70_Age_of_Steam.mp3",
    tags: ["trains", "engines", "locomotive", "train station", "train platform", "Ticket to Ride", "Railways of the World"],
    disabled: true,
  },
  song_71: {
    title: "Sleeping Dragon",
    mp3: "71_Sleeping_Dragon.mp3",
    tags: ["smaug", "treasure", "gold", "red dragon", "tiamat", "tolkien", "Dragon Rampage", "Dragon Run"],
    disabled: true,
  },
  song_72: {
    title: "Monster Attack!",
    mp3: "72_Monster_Attack.mp3",
    tags: ["godzilla", "tokyo", "japan", "king kong", "destruction", "chaos", "city", "urban", "King of Tokyo", "King of New York", "Rampage"],
  },
  song_73: {
    title: "Medieval Library",
    mp3: "73_Medieval_Library.mp3",
    tags: ["books", "quills", "scholars", "study", "peaceful", "quiet", "pages", "arcane"],
  },
  song_74: {
    title: "Zombies!",
    mp3: "74_Zombies!.mp3",
    tags: ["walking dead", "undead", "halloween", "brains", "flesh", "monster", "Dead of Winter", "Zombicide", "T.I.M.E. Stories", "Time Stories"],
  },
  song_75: {
    title: "Docks District",
    mp3: "75_Docks_District.mp3",
    tags: ["boats", "harbor", "shady", "water", "sea", "ships", "Le Havre", "Francis Drake"],
  },
  song_76: {
    title: "Alchemist's Lab",
    mp3: "76_Alchemists_Lab.mp3",
    tags: ["spells", "potions", "laboratory", "bubbling", "magic", "Alchemists"],
  },
  song_77: {
    title: "Abandoned Fair",
    mp3: "77_Abandoned_Fair.mp3",
    tags: ["apocalypse", "post-apocalyptic", "desolate", "eerie", "amusement park", "dystopia"],
  },
  song_78: {
    title: "Steampunk Airship",
    mp3: "78_Steampunk_Airship.mp3",
    tags: ["blimp", "dirigible", "victorian", "jules verne", "Kings of Air and Steam"],
    disabled: true,
  },
  song_79: {
    title: "Medieval Battle",
    mp3: "79_Medieval_Battle.mp3",
    tags: ["army", "armies", "horses", "weapons", "soldiers", "fight", "clash", "combat"],
  },
  song_80: {
    title: "Blacksmith Shoppe",
    mp3: "80_Blacksmith_Shoppe.mp3",
    tags: ["metal", "anvil", "horse", "armor", "iron", "forge", "Forge War", "King's Forge", "Kings Forge"],
    disabled: true,
  },
  song_81: {
    title: "1920s Speakeasy",
    mp3: "81_1920s_Speakeasy.mp3",
    tags: ["jazz age", "20s", "30s", "drink", "twenties", "flappers", "food", "bar", "tavern", "inn", "gangsters", "mobsters", "Bootleggers"],
    disabled: true,
  },
  song_82: {
    title: "Nightmare",
    mp3: "82_Nightmare.mp3",
    tags: ["ghosts", "spooky", "scary", "halloween", "terror", "fright"],
  },
  song_83: {
    title: "Haunted Ramparts",
    mp3: "83_Haunted_Ramparts.mp3",
    tags: ["ghosts", "spooky", "scary", "halloween", "terror", "fright", "hamlet"],
    disabled: true,
  },
  song_84: {
    title: "Lucha Libre!",
    mp3: "84_Lucha_Libre.mp3",
    tags: ["mexican", "wrestling", "arena", "crowds", "wwe", "wwf"],
  },
  song_85: {
    title: "Sewers",
    mp3: "85_Sewers.mp3",
    tags: ["dark", "dank", "dripping", "tunnel", "sewars", "quest", "dungeon", "water", "underground"],
  },
  song_86: {
    title: "Dark City",
    mp3: "86_Dark_City.mp3",
    tags: ["action", "mysterious", "television", "tv", "cyberpunk"],
  },
  song_87: {
    title: "Winter Festival",
    mp3: "87_Winter_Festival.mp3",
    tags: ["christmas", "xmas", "festivus", "holiday", "frozen", "ice", "fair"],
    disabled: true,
  },
  song_88: {
    title: "Lively Cafe",
    mp3: "88_Lively_Cafe.mp3",
    tags: ["coffee shop", "starbucks", "restaurant", "tea", "productivty", "tavern"],
    disabled: true,
  },
  song_89: {
    title: "Winter Woods",
    mp3: "89_Winter_Woods.mp3",
    tags: ["peaceful", "quiet", "solitude", "outdoors", "cold"],
  },
  song_90: {
    title: "Dungeon II: Mechanical",
    mp3: "90_Dungeon_II_Mechanical.mp3",
    tags: ["dwemer", "dwarf", "dwarven", "gears", "clockwork", "underground", "quest"],
  },
  song_91: {
    title: "Elven Glade",
    mp3: "91_Elven_Glade.mp3",
    tags: ["elves", "elf", "forest", "woods", "spirits", "tolkien", "peaceful", "magic", "sleeping"],
    disabled: true,
  },
  song_92: {
    title: "Skirmish",
    mp3: "92_Skirmish.mp3",
    tags: ["battle", "drama", "action", "fight", "clash", "medieval", "epic", "combat"],
  },
  song_93: {
    title: "Starship Medical",
    mp3: "93_Starship_Medical.mp3",
    tags: ["trek", "space", "station", "doctor", "starfleet"],
    disabled: true,
  },
  song_94: {
    title: "Noir Procedural",
    mp3: "94_Noir_Procedural.mp3",
    tags: ["police", "drama", "television", "tv", "intrigue", "investigation", "detective", "Deception"],
    disabled: true,
  },
  song_95: {
    title: "Arabesque",
    mp3: "95_Arabesque.mp3",
    tags: ["horses", "desert", "middle eastern", "nomad", "bedouin", "exotic", "warriors", "sand", "Tales of the Arabian Nights", "egypt"],
    disabled: true,
  },
  song_96: {
    title: "Windswept Plains",
    mp3: "96_Windswept_Plains_b.mp3",
    tags: ["indian", "native", "american", "horses", "prairie", "western", "cowboy"],
  },
  song_97: {
    title: "City Under Siege",
    mp3: "97_City_Under_Siege.mp3",
    tags: ["battle", "assault", "urban", "weapons", "gunfire", "military", "fight", "combat"],
  },
  song_98: {
    title: "Lost Mine",
    mp3: "98_Lost_Mine.mp3",
    tags: ["adventure", "tolkien", "khazad dum", "dwarf", "dwarven", "quest", "cave", "moria", "dungeon"],
  },
  song_99: {
    title: "Cavern of Lost Souls",
    mp3: "99_Cavern_of_Lost_Souls.mp3",
    tags: ["spirits", "ghosts", "wailing", "danger", "magic", "moria", "dungeon"],
  },
  song_100: {
    title: "Volcano",
    mp3: "100_Volcano.mp3",
    tags: ["hell", "bubbling", "sulphur", "devil", "inferno"],
  },
  song_101: {
    title: "Highway",
    mp3: "101_Highway.mp3",
    tags: ["road", "cars", "lynch", "hitch", "trip", "tv", "television"],
  },
  song_102: {
    title: "Vampire's Castle",
    mp3: "102_Vampire_Castle.mp3",
    tags: ["vampire", "gothic", "castle", "haunted", "dracula", "blood", "undead", "halloween", "monster", "strahd", "Ravenloft"],
    disabled: true,
  },
  song_103: {
    title: "Testing Chamber",
    mp3: "103_Testing_Chamber.mp3",
    tags: ["portal", "factory", "industrial", "machines"],
    disabled: true,
  },
  song_104: {
    title: "River Town",
    mp3: "104_River_Town.mp3",
    tags: ["elves", "elven", "elf", "water", "stream", "sleeping", "village"],
    disabled: true,
  },
  song_105: {
    title: "Weirder Things",
    mp3: "105_Weirder_Things_2.mp3",
    tags: ["80s", "synth", "tv", "television"],
  },
  song_106: {
    title: "Lunar Outpost",
    mp3: "106_Lunar_Outpost.mp3",
    tags: ["suspense", "abandoned", "machines", "industrial", "alien"],
  },
  song_107: {
    title: "Lonesome West",
    mp3: "107_Lonesome_West.mp3",
    tags: ["west", "western", "horses", "dusty", "Deadlands", "cowboys"],
    disabled: true,
  },
  song_108: {
    title: "Carnival",
    mp3: "108_Carnival.mp3",
    tags: ["fairground", "fair", "rides", "circus"],
  },
  song_109: {
    title: "747 Interior",
    mp3: "109_747_Interior.mp3",
    tags: ["aircraft", "airplane", "cabin", "white noise"],
    disabled: true,
  },
  song_110: {
    title: "Wild West Saloon",
    mp3: "110_Wild_West_Saloon.mp3",
    tags: ["west", "western", "ragtime", "music", "inn", "tavern", "Deadlands", "food", "drink"],
  },
  song_111: {
    title: "Orbital Promenade",
    mp3: "111_Orbital_Promenade.mp3",
    tags: ["space station", "star trek", "star wars", "future", "commerce", "shopping", "mall", "crowds"],
    disabled: true,
  },
  song_112: {
    title: "Ethereal Plane",
    mp3: "112_Ethereal_Plane.mp3",
    tags: ["astral", "peaceful", "abstract", "swirl", "light", "heaven"],
  },
  song_113: {
    title: "Astral Plane",
    mp3: "113_Astral_Plane.mp3",
    tags: ["ethereal", "dark", "abstract", "swirl", "heaven", "projection"],
    disabled: true,
  },
  song_114: {
    title: "Dwarven City",
    mp3: "114_Dwarven_City.mp3",
    tags: ["underground", "dark", "dwarf", "moria", "khazad dum", "forge"],
    disabled: true,
  },
  song_115: {
    title: "Antiquarian Study",
    mp3: "115_Antiquarian_Study.mp3",
    tags: ["mystery", "sleeping", "suspense", "victorian", "office", "library", "rain", "house"],
  },
  song_116: {
    title: "RavenPuff Common",
    mp3: "116_RavenPuff_Common.mp3",
    tags: ["Potter", "Hogwarts", "magic", "victorian", "fireplace", "library", "castle", "house", "wizard", "school", "witch"],
    disabled: true,
  },
  song_117: {
    title: "Crossroads",
    mp3: "117_Crossroads.mp3",
    tags: ["southern", "blues", "guitar", "bayou", "south", "rural", "country", "traffic"],
  },
  song_118: {
    title: "Spire:The Heart",
    mp3: "118_Spire_The_Heart_a.mp3",
    tags: ["decay", "blood", "insects", "rotting", "disease"],
  },
  song_119: {
    title: "Spire:Amaranth",
    mp3: "119_Spire_Amaranth_a.mp3",
    tags: ["ice", "crystalline", "frozen", "cold", "coins", "cruel", "winter"],
  },
  song_120: {
    title: "Spire:New Heaven",
    mp3: "120_Spire_New_Heaven.mp3",
    tags: ["wind", "mourning", "chants", "priests", "preachers", "zealots", "funeral", "dirges", "bells"],
    disabled: true,
  },
  song_121: {
    title: "Spire:Derelictus",
    mp3: "121_Spire_Derelictus.mp3",
    tags: ["dripping", "dark", "chants", "drow", "slum", "poverty", "decay", "ruins", "magic"],
    disabled: true,
  },
  song_122: {
    title: "Spire:The Ministry",
    mp3: "122_Spire_The_Ministry.mp3",
    tags: ["secrets", "whispers", "prayer", "temple", "religion", "sanctuary", "chants", "ritual", "rites", "church"],
  },
  song_123: {
    title: "Spire:The Hatchery",
    mp3: "123_Spire_The_Hatchery.mp3",
    tags: ["insects", "spiders", "creepy", "skittering", "nursery", "dank", "dark"],
    disabled: true,
  },
  song_124: {
    title: "Spire:The Vermissian",
    mp3: "124_Spire_The_Vermissian.mp3",
    tags: ["vibrations", "machinery", "wind", "tunnels", "train", "unreality"],
    disabled: true,
  },
  song_125: {
    title: "Existential Dread",
    mp3: "125_Existential_Dread.mp3",
    tags: ["125", "Halloween", "fear", "buried", "paranoid", "paranoia", "terror", "scary"],
  },
  song_126: {
    title: "Endless Voyage",
    mp3: "126_Endless_Voyage.mp3",
    tags: ["synth", "journey", "space", "exploration", "wonder", "planets", "stars", "nebula"],
    disabled: true,
  },
  song_127: {
    title: "Car Chase!",
    mp3: "127_Car_Chase_a.mp3",
    tags: ["70s", "cops", "police", "funk", "tv", "cars", "highway", "hotrods", "race", "speed", "television"],
  },
  song_128: {
    title: "Waiting Time",
    mp3: "128_Waiting_Time.mp3",
    tags: ["clockwork", "gnomes", "gears", "patience", "funny", "humor", "creepy", "crazy", "building", "work"],
    disabled: true,
  },
  song_129: {
    title: "Weirder Things: 2",
    mp3: "129_Weirder_Things_2.mp3",
    tags: ["80s", "synth", "tv", "television"],
  },
  song_130: {
    title: "Russian Winter",
    mp3: "130_Russian_Winter.mp3",
    tags: ["snow", "ice", "slavic", "cold", "wind", "north", "barren"],
  },
  song_131: {
    title: "The Bog Standard",
    mp3: "131_The_Bog_Standard.mp3",
    tags: ["tavern", "meeting", "inn", "hearth", "food", "drink"],
  },
  song_132: {
    title: "Open Ocean",
    mp3: "132_Open_Ocean.mp3",
    tags: ["water", "waves", "sea", "peaceful", "productivty"],
  },
  song_133: {
    title: "Halfling Festival",
    mp3: "133_Halfling_Festival.mp3",
    tags: ["party", "wedding", "dance", "hobbits", "village", "fair"],
  },
  song_134: {
    title: "Carriage Journey",
    mp3: "134_Carriage_Journey.mp3",
    tags: ["horses", "traveling", "buggy", "cart", "stagecoach", "hansom", "travel", "coach", "rain"],
  },
  song_135: {
    title: "Dark Matter",
    mp3: "135_Dark_Matter.mp3",
    tags: ["infinity", "cosmos", "universe", "celestial", "cyberpunk", "planets", "computers", "abstract"],
    disabled: true,
  },
  song_136: {
    title: "Temple of Helm",
    mp3: "136_Temple_Of_Helm.mp3",
    tags: ["prayer", "gods", "religion", "sanctuary", "chants", "ritual", "rites", "holy", "church"],
    disabled: true,
  },
  song_137: {
    title: "Mill Town",
    mp3: "137_Mill_Town_a.mp3",
    tags: ["river", "stream", "village", "water"],
  },
  song_138: {
    title: "Desert Winds",
    mp3: "138_Desert_Winds.mp3",
    tags: ["storm", "sandstorm", "sand", "arabian", "weather", "dust", "haboob", "Tales of the Arabian Nights", "egypt"],
    disabled: true,
  },
  song_139: {
    title: "Sunken Temple",
    mp3: "139_Sunken_Temple.mp3",
    tags: ["underwater", "water", "deep", "sunken pyramid", "ocean", "sea", "depths", "dive", "scuba", "Aquasphere", "church"],
    disabled: true,
  },
  song_140: {
    title: "Dark Future",
    mp3: "140_Dark_Future.mp3",
    tags: ["neon", "cyberpunk", "noir", "space", "gritty", "metallic", "urban"],
  },
  song_141: {
    title: "Hermit Hut",
    mp3: "141_Hermit_Hut.mp3",
    tags: ["wind", "cabin", "shack", "hovel", "house", "witch", "crone", "lonely", "woods"],
  },
  song_142: {
    title: "Mummy's Tomb",
    mp3: "142_Mummys_Tomb.mp3",
    tags: ["egypt", "pharoah", "pyramid", "burial", "undead", "desert", "sarcophagus"],
    disabled: true,
  },
  song_143: {
    title: "Elegant Dinner Party",
    mp3: "143_Elegant_Dinner_Party.mp3",
    tags: ["supper", "dining", "jane austen", "social", "entertaining", "downton abbey", "society"],
    disabled: true,
  },
  song_144: {
    title: "War Zone",
    mp3: "144_War_Zone.mp3",
    tags: ["warfare", "helicopters", "combat", "huey", "urban", "shelling", "city", "airstrike"],
  },
  song_145: {
    title: "Cotton Club",
    mp3: "145_Cotton_Club_CLEAN.mp3",
    tags: ["jazz", "harlem", "club", "bar", "speakeasy", "tavern", "city", "urban", "1920", "1930", "1940", "cthulhu"],
    disabled: true,
  },
  song_146: {
    title: "Floating Ice Castle",
    mp3: "146_Floating_Ice_Castle.mp3",
    tags: ["palace", "frozen", "fortress", "clouds", "giants", "cold", "flying", "sky", "skyreach"],
  },
  song_147: {
    title: "Graveyard",
    mp3: "147_Graveyard.mp3",
    tags: ["tomb", "castle", "strahd", "Dracula", "vampire", "wolf", "scary", "spooky", "gothic", "haunted", "monster", "Ravenloft"],
    disabled: true,
  },
  song_148: {
    title: "Barovian Castle",
    mp3: "148_Barovian_Castle.mp3",
    tags: ["Strahd", "Dracula", "vampire", "wolf", "scary", "spooky", "gothic", "haunted", "monster", "Ravenloft"],
  },
  song_149: {
    title: "Lakeside Camp",
    mp3: "149_Lakeside_Camp.mp3",
    tags: ["river", "stream", "water", "campsite", "campfire", "calm", "peaceful", "relaxing"],
  },
  song_150: {
    title: "Loop Tales",
    mp3: "150_Loop_Tales.mp3",
    tags: ["technolgy", "Tales from the Loop", "cyberpunk", "abstract", "dystopia", "80s", "synth", "tv", "television"],
    disabled: true,
  },
  song_151: {
    title: "Metropolis Fanfare",
    mp3: "151_Metropolis_Fanfare.mp3",
    tags: ["combat", "battle", "action", "drama", "steampunk"],
    disabled: true,
  },
  song_152: {
    title: "Nostromo",
    mp3: "152_Nostromo.mp3",
    tags: ["spaceship", "salvage", "aliens", "reavers", "halloween", "space", "hypersleep"],
  },
  song_153: {
    title: "Secret Garden",
    mp3: "153_Secret_Garden.mp3",
    tags: ["elves", "elven", "elf", "forest", "woods", "spirits", "tolkien", "peaceful", "magic", "sleeping"],
  },
  song_154: {
    title: "Artist's Garret",
    mp3: "154_Artists_Garret.mp3",
    tags: ["attic", "rain", "writing", "fireplace", "solitude", "peaceful", "shack"],
    disabled: true,
  },
  song_155: {
    title: "Outpost 31",
    mp3: "155_Outpost_31.mp3",
    tags: ["antarctica", "arctic", "snow", "ice", "synth", "john carpenter", "thing", "the thing", "morricone", "cold", "winter"],
  },
  song_156: {
    title: "Star Freighter",
    mp3: "156_Star_Freighter.mp3",
    tags: ["cargo", "space", "spaceship", "peaceful", "aliens", "salvage"],
    disabled: true,
  },
  song_157: {
    title: "Field of Heroes",
    mp3: "157_Field_of_Heroes.mp3",
    tags: ["battle", "drama", "action", "fight", "clash", "medieval", "epic", "heroic", "combat"],
    disabled: true,
  },
  song_158: {
    title: "Waterkeep",
    mp3: "158_Waterkeep.mp3",
    tags: ["medieval", "city", "town", "Waterdeep", "society"],
  },
  song_159: {
    title: "Stables",
    mp3: "159_Stables.mp3",
    tags: ["medieval", "horses", "hitch", "grooming", "livestock", "stalls", "animals"],
  },
  song_160: {
    title: "Shanghai 1930s",
    mp3: "160_Shanghai_1930s.mp3",
    tags: ["jazz", "china", "asia", "asian", "orient", "cthulhu", "city", "urban", "crime", "1920", "1940"],
    disabled: true,
  },
  song_161: {
    title: "Forest: Day",
    mp3: "161_Forest_Day.mp3",
    tags: ["quiet", "breeze", "trees", "birds", "wind", "sleeping", "productivty"],
  },
  song_162: {
    title: "Dark Angel",
    mp3: "162_Dark_Angel.mp3",
    tags: ["action", "drama", "synth", "90s", "boss", "fight", "epic", "battle", "gothic"],
  },
  song_163: {
    title: "Medieval Fair",
    mp3: "163_Medieval_Fair.mp3",
    tags: ["festival", "town", "village", "market", "party", "bazaar"],
  },
  song_164: {
    title: "Cistern",
    mp3: "164_Cistern.mp3",
    tags: ["dark", "dank", "dripping", "tunnel", "sewars", "underground", "water"],
  },
  song_165: {
    title: "RMS Titanic",
    mp3: "165_RMS_Titanic.mp3",
    tags: ["ocean", "sea", "ships", "steamer", "boats", "luxury", "travel", "elegant"],
    disabled: true,
  },
  song_166: {
    title: "Quiet Cove",
    mp3: "166_Quiet_Cove.mp3",
    tags: ["ocean", "sea", "ships", "sail", "pirates", "Saltmarsh", "anchor", "inlet", "water", "tropics", "peaceful"],
    disabled: true,
  },
  song_167: {
    title: "Fishing Village",
    mp3: "167_Fishing_Village.mp3",
    tags: ["ocean", "sea", "boats", "town", "medieval", "Saltmarsh", "docks", "water", "peaceful"],
  },
  song_168: {
    title: "Neon Drive",
    mp3: "168_Neon_Drive.mp3",
    tags: ["action", "drama", "synth", "boss", "fight", "epic", "battle", "gothic", "cyberpunk", "Shadowrun", "combat"],
  },
  song_169: {
    title: "The Feywild",
    mp3: "169_The_Feywild.mp3",
    tags: ["peaceful", "forest", "nature", "trees", "breeze", "quiet", "ethereal"],
  },
  song_170: {
    title: "The Underdark",
    mp3: "170_The_Underdark.mp3",
    tags: ["dungeon", "underground", "dark", "drow", "mysterious", "dangerous"],
  },
  song_171: {
    title: "Cry Havoc",
    mp3: "171_Cry_Havoc.mp3",
    tags: ["battle", "drama", "action", "fight", "clash", "medieval", "epic", "heroic", "combat"],
  },
  song_172: {
    title: "Castle Jail",
    mp3: "172_Castle_Jail.mp3",
    tags: ["dungeon", "prison", "cell", "torture", "dark", "dank", "dripping"],
    disabled: true,
  },
  song_173: {
    title: "Robotics Lab",
    mp3: "173_Robotics_Lab.mp3",
    tags: ["technolgy", "hi-tech", "spaceship", "spacestation", "facility", "laboratory", "robots", "space station"],
  },
  song_174: {
    title: "Wizard's Tower",
    mp3: "174_Wizards_Tower.mp3",
    tags: ["magic", "heroic", "drama", "action", "magical"],
  },
  song_175: {
    title: "Royal Court",
    mp3: "175_Royal_Court.mp3",
    tags: ["king", "queen", "royalty", "palace", "monarch", "prince", "medieval", "imperial"],
  },
  song_176: {
    title: "Barren Wastes",
    mp3: "176_Barren_Wastes.mp3",
    tags: ["desert", "steppes", "lonely", "solitude", "wind", "tundra", "plains", "arctic", "alien", "planet"],
    disabled: true,
  },
  song_177: {
    title: "Tavern Music",
    mp3: "177_Tavern_Music.mp3",
    tags: ["inn", "hearth", "meeting", "bard", "dance", "tavern"],
  },
  song_178: {
    title: "Ice Throne",
    mp3: "178_Ice_Throne.mp3",
    tags: ["cavern", "frozen", "cold", "lich", "cave", "tundra", "snow", "winter"],
  },
  song_179: {
    title: "Cyberpunk City",
    mp3: "179_Cyberpunk_City.mp3",
    tags: ["urban", "future", "blade runner", "Shadowrun", "rain", "matrix"],
    disabled: true,
  },
  song_180: {
    title: "Abandoned Windmill",
    mp3: "180_Abandoned_Windmill.mp3",
    tags: ["rural", "country", "landscape", "building", "ominous", "medieval", "desolate"],
  },
  song_181: {
    title: "Cyberpunk Bar",
    mp3: "181_Cyberpunk_Bar.mp3",
    tags: ["urban", "future", "blade runner", "Shadowrun", "tavern", "matrix", "club"],
  },
  song_182: {
    title: "Country Village",
    mp3: "182_Country_Village.mp3",
    tags: ["rural", "town", "medieval", "peaceful", "farm"],
  },
  song_183: {
    title: "Sea of Moving Ice",
    mp3: "183_Sea_of_Moving_Ice.mp3",
    tags: ["ocean", "storm", "waves", "ominous", "glacier", "water", "winter"],
    disabled: true,
  },
  song_184: {
    title: "Underground Lake",
    mp3: "184_Underground_Lake.mp3",
    tags: ["water", "cave", "cavern", "mountain"],
    disabled: true,
  },
  song_185: {
    title: "Gravity",
    mp3: "185_Gravity.mp3",
    tags: ["space", "orbit", "tension", "ominous", "drama", "action", "cyberpunk"],
  },
  song_186: {
    title: "Haunted",
    mp3: "186_Haunted.mp3",
    tags: ["scary", "eerie", "halloween", "ghosts", "spooky", "graveyard", "monsters"],
  },
  song_187: {
    title: "Endgame",
    mp3: "187_Endgame.mp3",
    tags: ["battle", "drama", "action", "fight", "clash", "boss", "epic", "heroic", "combat"],
  },
  song_188: {
    title: "Barovian Village",
    mp3: "188_Barovian_Village.mp3",
    tags: ["mountain", "city", "town", "medieval", "quiet", "gothic", "strahd", "dracula", "Ravenloft"],
  },
  song_189: {
    title: "Yuletide",
    mp3: "189_Yuletide.mp3",
    tags: ["Christmas", "fireplace", "peaceful", "winter", "snow", "holiday"],
    disabled: true,
  },
  song_190: {
    title: "1940s Boardwalk",
    mp3: "190_1940s_Boardwalk.mp3",
    tags: ["seaside", "ocean", "beach", "1940s", "1930s", "cthulhu"],
    disabled: true,
  },
  song_191: {
    title: "Dying World",
    mp3: "191_Dying_World.mp3",
    tags: ["alien", "solitude", "wind", "dystopia", "crumble", "decay"],
    disabled: true,
  },
  song_192: {
    title: "Swamp Planet",
    mp3: "192_Swamp_Planet.mp3",
    tags: ["alien", "jungle", "humid", "insects", "water", "humid", "dagobah"],
    disabled: true,
  },
  song_193: {
    title: "The Steppes",
    mp3: "193_The_Steppes.mp3",
    tags: ["drums", "war", "battle", "army", "mongolian", "skirmish", "combat", "action", "fight"],
  },
  song_194: {
    title: "Tarrasque Interior",
    mp3: "194_Tarrasque_Interior.mp3",
    tags: ["monster", "dank", "wet", "ominous", "mysterious", "dark"],
  },
  song_195: {
    title: "Shopping Mall",
    mp3: "195_Shopping_Mall.mp3",
    tags: ["crowds", "promenade", "galleria", "stores", "80s", "shops"],
  },
  song_196: {
    title: "Crossing the Styx",
    mp3: "196_Crossing_the_Styx.mp3",
    tags: ["boat", "water", "Charon", "row", "hades", "ominous", "hell", "ferry", "ferryman"],
    disabled: true,
  },
  song_197: {
    title: "Battle of the Amazons",
    mp3: "197_Battle_of_the_Amazons.mp3",
    tags: ["action", "fight", "clash", "combat", "heroic", "war", "combat"],
    disabled: true,
  },
  song_198: {
    title: "Shadowfell",
    mp3: "198_Shadowfell.mp3",
    tags: ["scary", "eerie", "dark", "ominous", "shadow", "ethereal"],
    disabled: true,
  },
  song_199: {
    title: "Sun Dappled Trail",
    mp3: "199_Sun_Dappled_Trail.mp3",
    tags: ["forest", "horses", "peaceful", "woods", "trees", "travel", "journey"],
  },
  song_200: {
    title: "Druid Hilltop",
    mp3: "200_Druid_Hilltop.mp3",
    tags: ["occult", "ritual", "summoning", "Yester Hill", "strahd", "wind", "chant"],
  },
  song_201: {
    title: "Haven",
    mp3: "201_Haven.mp3",
    tags: ["peaceful", "rain", "calm", "mourning", "thunder", "drama", "heroic"],
    disabled: true,
  },
  song_202: {
    title: "Heart: Drowned",
    mp3: "202_Heart_Drowned.mp3",
    tags: ["water", "sewars", "cave", "tunnel", "flood", "waves"],
    disabled: true,
  },
  song_203: {
    title: "Heart: Briar",
    mp3: "203_Heart_Briar.mp3",
    tags: ["forest", "woods", "beasts", "jungle", "birds", "crows"],
  },
  song_204: {
    title: "Heart: Meat Corridor",
    mp3: "204_Heart_Meat_Corridor.mp3",
    tags: ["tunnel", "decay", "rot", "flesh", "insects"],
    disabled: true,
  },
  song_205: {
    title: "Heart: Absolution",
    mp3: "205_Heart_Absolution.mp3",
    tags: ["chaos", "nightmare", "dreams", "alien", "terror"],
  },
  song_206: {
    title: "Heart: High Rise",
    mp3: "206_Heart_High_Rise.mp3",
    tags: ["ropes", "bridges", "wind", "buildings", "breeze", "crows", "vents"],
  },
  song_207: {
    title: "Biodome",
    mp3: "207_Biodome.mp3",
    tags: ["peaceful", "breeze", "drama", "relaxing", "technology", "dome", "greenhouse"],
  },
  song_208: {
    title: "Ghost Town",
    mp3: "208_Ghost_Town.mp3",
    tags: ["desolate", "rural", "village", "eerie", "abandoned", "ominous", "peaceful"],
  },
  song_209: {
    title: "Rat Battle",
    mp3: "209_Rat_Battle.mp3",
    tags: ["fight", "battle", "action", "skirmish", "clash", "melee", "scuffle", "combat"],
  },
  song_210: {
    title: "Temple Garden",
    mp3: "210_Temple_Garden.mp3",
    tags: ["peaceful", "quiet", "zen", "water", "fountain", "calm", "heal"],
    disabled: true,
  },
  song_211: {
    title: "Thieves' Guild",
    mp3: "211_Thieves_Guild.mp3",
    tags: ["action", "stealth", "cyberpunk", "mysterious", "sneak", "tv", "dark", "shadows"],
  },
  song_212: {
    title: "Witch Mountain",
    mp3: "212_Witch_Mountain.mp3",
    tags: ["action", "magic", "fight", "battle", "heroic", "war", "magical", "heroic", "combat"],
  },
  song_213: {
    title: "Burning Village",
    mp3: "213_Burning_Village.mp3",
    tags: ["fire", "chaos", "destruction", "town", "flames", "waste", "hell"],
  },
  song_214: {
    title: "Castle Kitchen",
    mp3: "214_Castle_Kitchen.mp3",
    tags: ["medieval", "cooking", "food", "restaurant", "feast", "oven"],
    disabled: true,
  },
  song_215: {
    title: "Space Battle",
    mp3: "215_Space_Battle.mp3",
    tags: ["action", "combat", "Star Wars", "spaceship", "starship", "space opera", "lasers"],
  },
  song_216: {
    title: "Waterkeep: Night",
    mp3: "216_Waterkeep_Night.mp3",
    tags: ["medieval", "city", "town", "Waterdeep", "society", "night", "quiet"],
  },
  song_217: {
    title: "Storm at Sea",
    mp3: "217_Storm_at_Sea.mp3",
    tags: ["sailing", "ship", "ocean", "waves", "nautical", "navy", "sail", "squall", "boat"],
    disabled: true,
  },
  song_218: {
    title: "Sleeping Ogre",
    mp3: "218_Sleeping_Ogre.mp3",
    tags: ["stealth", "dungeon", "quiet", "tense", "sneak", "dark", "shadows", "monster"],
    disabled: true,
  },
  song_219: {
    title: "Tinkerer's Workshop",
    mp3: "219_Tinkerers_Workshop.mp3",
    tags: ["gnomes", "shop", "machines", "funny", "steampunk", "sneak", "stealth", "comedy"],
  },
  song_220: {
    title: "Wuxia Village",
    mp3: "220_Wuxia_Village.mp3",
    tags: ["Asian", "Chinese", "China", "martial arts", "kung fu", "rural", "mountain", "town"],
  },
  song_221: {
    title: "Sunken Treasure",
    mp3: "221_Sunken_Treasure.mp3",
    tags: ["underwater", "water", "deep", "ocean", "sea", "depths", "dive", "scuba", "shipwreck"],
    disabled: true,
  },
  song_222: {
    title: "Wuxia Tea House",
    mp3: "222_Wuxia_Tea_House.mp3",
    tags: ["Asian", "Chinese", "China", "martial arts", "kung fu", "rural", "peaceful", "village"],
    disabled: true,
  },
  song_223: {
    title: "Salt Marsh",
    mp3: "223_Salt_Marsh.mp3",
    tags: ["ocean", "sea", "water", "Saltmarsh", "peaceful", "breeze", "birds", "reeds"],
    disabled: true,
  },
  song_224: {
    title: "Mansion: Night",
    mp3: "224_Mansion_Night.mp3",
    tags: ["stealth", "search", "house", "sneak", "dark", "shadows", "mysterious"],
  },
  song_225: {
    title: "New Orleans Noir",
    mp3: "225_New_Orleans_Noir.mp3",
    tags: ["1920s", "1930s", "gothic", "cthulhu", "urban", "city", "mystery"],
    disabled: true,
  },
  song_226: {
    title: "60s Computer Lab",
    mp3: "226_60s_Computer_Lab.mp3",
    tags: ["1950s", "1960s", "synthesizer", "tension", "technology", "laboratory", "science"],
    disabled: true,
  },
  song_227: {
    title: "Terror in the Woods",
    mp3: "227_Terror_in_the_Woods.mp3",
    tags: ["lovecraft", "action", "chase", "tension", "monsters", "battle", "combat"],
  },
  song_228: {
    title: "Mushroom Forest",
    mp3: "228_Mushroom_Forest.mp3",
    tags: ["ethereal", "psychedelic", "trippy", "peaceful", "calm", "quiet"],
    disabled: true,
  },
  song_229: {
    title: "Interrogation Room",
    mp3: "229_Interrogation_Room.mp3",
    tags: ["cyberpunk", "police", "tension", "tense", "action", "tv", "sneak", "dark", "stealth"],
  },
  song_230: {
    title: "All Hallows' Eve",
    mp3: "230_All_Hallows_Eve.mp3",
    tags: ["Strahd", "Dracula", "vampire", "wolf", "scary", "spooky", "gothic", "haunted", "monster", "Halloween", "Ravenloft"],
  },
  song_231: {
    title: "Icebound Town",
    mp3: "231_Icebound_Town.mp3",
    tags: ["cold", "winter", "ice", "frozen", "north", "frost", "Frostmaiden", "Icewind Dale", "arctic", "village"],
  },
  song_232: {
    title: "Mech War",
    mp3: "232_Mech_War.mp3",
    tags: ["battle", "war", "action", "robot", "Warhammer", "drama", "fight", "boss", "epic", "combat"],
    disabled: true,
  },
  song_233: {
    title: "The Orrery",
    mp3: "233_The_Orrery.mp3",
    tags: ["church", "temple", "cathedral", "mechanical", "peaceful", "ritual", "peaceful", "steampunk"],
    disabled: true,
  },
  song_234: {
    title: "Lush World",
    mp3: "234_Lush_World.mp3",
    tags: ["peaceful", "quiet", "water", "calm", "ethereal", "psychedelic", "birds"],
  },
  song_235: {
    title: "Rainy Village",
    mp3: "235_Rainy_Village.mp3",
    tags: ["peaceful", "town", "rain", "thunder", "horses", "rural"],
    disabled: true,
  },
  song_236: {
    title: "Defiled Temple",
    mp3: "236_Defiled_Temple.mp3",
    tags: ["dungeon", "monsters", "dark", "cult", "church", "occult", "ritual"],
  },
  song_237: {
    title: "Training Grounds",
    mp3: "237_Training_Grounds.mp3",
    tags: ["swords", "fight", "spar", "battle", "melee", "clash", "skirmish", "action", "castle", "combat"],
  },
  song_238: {
    title: "Mind Flayer Chamber",
    mp3: "238_Mind_Flayer_Chamber.mp3",
    tags: ["illithid", "dungeon", "suspense", "brain", "elder brain", "action"],
  },
  song_239: {
    title: "Nordic Noir",
    mp3: "239_Nordic_Noir.mp3",
    tags: ["police", "drama", "television", "tv", "intrigue", "investigation", "detective", "Scandinavian"],
  },
  song_240: {
    title: "Throne Room",
    mp3: "240_Throne_Room.mp3",
    tags: ["palace", "regal", "royalty", "court", "gossip", "king", "queen", "Love Letter", "salon"],
  },
  song_241: {
    title: "Pirates!",
    mp3: "241_Pirates.mp3",
    tags: ["sailing", "ship", "ocean", "boat", "nautical", "sea", "adventure"],
  },
  song_242: {
    title: "Spider's Den",
    mp3: "242_Spiders_Den.mp3",
    tags: ["dark", "cave", "lair", "dungeon", "boss", "aragog", "tunnel", "web", "insects"],
  },
  song_243: {
    title: "Jungle Ruins",
    mp3: "243_Jungle_Ruins.mp3",
    tags: ["aztec", "mayan", "temple", "forest", "birds", "humid", "insects"],
  },
  song_244: {
    title: "Vikings",
    mp3: "244_Vikings.mp3",
    tags: ["ocean", "sail", "boats", "battle", "drums", "action", "Scandinavian", "Norse", "Nordic", "war", "combat"],
  },
  song_245: {
    title: "Secret Facility",
    mp3: "245_Secret_Facility.mp3",
    tags: ["cyberpunk", "tension", "tv", "drama", "police", "spy", "spies", "noir"],
  },
  song_246: {
    title: "Magic Shoppe",
    mp3: "246_Magic_Shoppe.mp3",
    tags: ["Harry Potter", "Olivander", "general store", "store", "potions", "supplies", "Diagon Alley"],
    disabled: true,
  },
  song_247: {
    title: "Oregon Trail",
    mp3: "247_Oregon_Trail.mp3",
    tags: ["west", "America", "wagon", "wagon train", "horse", "oxen", "journey", "travel", "western"],
    disabled: true,
  },
  song_248: {
    title: "Alien Reactor",
    mp3: "248_Alien_Reactor.mp3",
    tags: ["Cthulhu", "dark", "scary", "tense", "tension", "monster", "lovecraft"],
    disabled: true,
  },
  song_249: {
    title: "Steampunk Station",
    mp3: "249_Steampunk_Station.mp3",
    tags: ["victorian", "trains", "machines", "clocks", "gears", "airship"],
    disabled: true,
  },
  song_250: {
    title: "Wolf Pens",
    mp3: "250_Wolf_Pens.mp3",
    tags: ["wolves", "dungeon", "jail", "cellar", "castle", "monsters", "suspense"],
    disabled: true,
  },
  song_251: {
    title: "Candledeep",
    mp3: "251_Candledeep.mp3",
    tags: ["library", "Candlekeep", "fortress", "books", "knowledge", "monks", "chant"],
    disabled: true,
  },
  song_252: {
    title: "Vault of Terror",
    mp3: "252_Vault_of_Terror.mp3",
    tags: ["tomb", "dungeon", "dark", "occult", "tomb of horror", "underground"],
  },
  song_253: {
    title: "Submerged",
    mp3: "253_Submerged.mp3",
    tags: ["ocean", "water", "dark", "calm", "peaceful", "quiet", "ethereal", "scuba"],
    disabled: true,
  },
  song_254: {
    title: "Desert Planet Souk",
    mp3: "254_Desert_Planet_Souk.mp3",
    tags: ["sand", "tatooine", "jawas", "droids", "Star Wars", "alien", "bazaar", "market"],
    disabled: true,
  },
  song_255: {
    title: "The Hearth Inn",
    mp3: "255_The_Hearth_Inn.mp3",
    tags: ["tavern", "pub", "inn", "Candlekeep", "bard", "hearth"],
  },
  song_256: {
    title: "Ice Dragon",
    mp3: "256_Ice_Dragon.mp3",
    tags: ["snow", "battle", "boss", "dragon", "monsters", "fight", "action", "war", "combat"],
  },
  song_257: {
    title: "Country Workshop",
    mp3: "257_Country_Workshop.mp3",
    tags: ["rural", "town", "medieval", "peaceful", "farm", "blacksmith", "tinker", "village"],
    disabled: true,
  },
  song_258: {
    title: "Blighted Forest",
    mp3: "258_Blighted_Forest.mp3",
    tags: ["rot", "disease", "evil", "corrupted", "poisoned", "tainted", "trees", "grove"],
  },
  song_259: {
    title: "Grand Theater",
    mp3: "259_Grand_Theater.mp3",
    tags: ["theatre", "drama", "auditorium", "playhouse", "hall", "orchestra"],
    disabled: true,
  },
  song_260: {
    title: "Skyship",
    mp3: "260_Skyship.mp3",
    tags: ["airship", "flying", "sailing", "transport"],
  },
  song_261: {
    title: "Unto the Breach",
    mp3: "261_Unto_the_Breach.mp3",
    tags: ["battle", "war", "siege", "skirmish", "army", "soldiers", "fight", "combat"],
  },
  song_262: {
    title: "Victorian Slums",
    mp3: "262_Victorian_Slums.mp3",
    tags: ["london", "dickens", "city", "ghetto", "urban", "Jack the Ripper", "Sherlock", "19th century"],
    disabled: true,
  },
  song_263: {
    title: "Mysterious Grotto",
    mp3: "263_Mysterious_Grotto.mp3",
    tags: ["cave", "dark", "lair", "cavern", "dungeon", "mountain"],
  },
  song_264: {
    title: "Base Assault",
    mp3: "264_Base_Assault.mp3",
    tags: ["battle", "war", "action", "fight", "boss", "epic", "combat"],
  },
  song_265: {
    title: "Shrine of Talos",
    mp3: "265_Shrine_of_Talos.mp3",
    tags: ["temple", "church", "cult", "mountain", "storm", "thunder", "lightning", "wind"],
    disabled: true,
  },
  song_266: {
    title: "Orbital Prison Break",
    mp3: "266_Orbital_Prison_Break.mp3",
    tags: ["battle", "war", "action", "fight", "boss", "combat", "epic"],
  },
  song_267: {
    title: "Court of the Count",
    mp3: "267_Court_of_the_Count.mp3",
    tags: ["Strahd", "Dracula", "castle", "cthulhu", "vampire", "library", "scary", "barovia", "Ravenloft"],
  },
  song_268: {
    title: "Starforged: Space",
    mp3: "268_Starforged_Space.mp3",
    tags: ["interstellar", "stars", "space", "star trek", "space travel"],
    disabled: true,
  },
  song_269: {
    title: "Starforged: Planetside",
    mp3: "269_Starforged_Planetside.mp3",
    tags: ["exploration", "alien", "planet", "star trek"],
    disabled: true,
  },
  song_270: {
    title: "Starforged: Sojourn",
    mp3: "270_Starforged_Sojourn.mp3",
    tags: ["settlement", "outpost", "colony", "star trek", "alien"],
    disabled: true,
  },
  song_271: {
    title: "Starforged: Fray",
    mp3: "271_Starforged_Fray.mp3",
    tags: ["action", "combat", "Star Wars", "spaceship", "starship", "space", "lasers", "battle"],
    disabled: true,
  },
  song_272: {
    title: "Starforged: Vault",
    mp3: "272_Starforged_Vault.mp3",
    tags: ["abandoned", "derelict", "relics", "technology", "alien"],
    disabled: true,
  },
  song_273: {
    title: "Arcane Clockworks",
    mp3: "273_Arcane_Clockworks.mp3",
    tags: ["steampunk", "mechanical", "gears", "dance", "1920s", "1930s", "gnome", "workshop"],
    disabled: true,
  },
  song_274: {
    title: "Jungle Shaman",
    mp3: "274_Jungle_Shaman.mp3",
    tags: ["rites", "jungle", "beach", "waterfall", "spirits", "ritual", "voodoo"],
  },
  song_275: {
    title: "Lorekeeper Grove",
    mp3: "275_Lorekeeper_Grove.mp3",
    tags: ["druids", "elven", "elf", "forest", "woods", "ritual", "peaceful", "emerald enclave"],
  },
  song_276: {
    title: "Forge of Fury",
    mp3: "276_Forge_of_Fury.mp3",
    tags: ["dwarf", "dwarven", "smith", "fire", "metal", "blacksmith", "moria", "khazad dum"],
    disabled: true,
  },
  song_277: {
    title: "A New Beginning",
    mp3: "277_A_New_Beginning.mp3",
    tags: ["peaceful", "ocean", "waves", "planet", "dawn", "exploration"],
  },
  song_278: {
    title: "Farmyard",
    mp3: "278_Farmyard.mp3",
    tags: ["rural", "medieval", "town", "village", "agriculture", "peaceful"],
  },
  song_279: {
    title: "Blighted Farm",
    mp3: "279_Blighted_Farm.mp3",
    tags: ["rural", "medieval", "village", "town", "diseased", "evil", "defiled", "rotten"],
    disabled: true,
  },
  song_280: {
    title: "The City Above",
    mp3: "280_The_City_Above.mp3",
    tags: ["urban", "skyscraper", "city", "rooftop", "cyberpunk"],
  },
  song_281: {
    title: "Escape from Shadow",
    mp3: "281_Escape_from_Shadow.mp3",
    tags: ["action", "combat", "battle", "drama", "army", "adventure"],
  },
  song_282: {
    title: "The Wild Hunt",
    mp3: "282_The_Wild_Hunt.mp3",
    tags: ["action", "combat", "chase", "horses", "horseback", "forest", "woods", "pagan", "Witcher"],
  },
  song_283: {
    title: "Pattern Recognition",
    mp3: "283_Pattern_Recognition.mp3",
    tags: ["cyberpunk", "computers", "stealth", "suspense", "tech", "noir", "drama", "investigation"],
  },
  song_284: {
    title: "Oasis City",
    mp3: "284_Oasis_City.mp3",
    tags: ["souk", "arab", "arabian", "sand", "camels", "market", "desert", "camels", "spice", "Ank'Harel", "Ank Harel"],
    disabled: true,
  },
  song_285: {
    title: "High Rannoc Village",
    mp3: "285_High_Rannoc_Village.mp3",
    tags: ["Apothecaria", "town", "village", "mountain"],
  },
  song_286: {
    title: "Blastfire Bog",
    mp3: "286_Blastfire_Bog.mp3",
    tags: ["Apothecaria", "swamp", "insects", "goblins", "dryads", "ruins"],
  },
  song_287: {
    title: "The Strange",
    mp3: "287_The_Strange.mp3",
    tags: ["Apothecaria", "city", "chaos", "chaotic", "demons", "magical"],
    disabled: true,
  },
  song_288: {
    title: "Everdeep",
    mp3: "288_Everdeep.mp3",
    tags: ["ocean", "sea", "underwater", "Netherdeep", "depths", "water", "abyss"],
  },
  song_289: {
    title: "Ancient Artifact",
    mp3: "289_Ancient_Artifact.mp3",
    tags: ["alien", "object", "temple", "Dune", "Numenera", "technology"],
  },
  song_290: {
    title: "Wagon Ride",
    mp3: "290_Wagon_Ride.mp3",
    tags: ["horse", "carriage", "cart", "oxen", "ox", "oxcart", "travel", "drama", "Skyrim"],
  },
  song_291: {
    title: "Invstigator's Office",
    mp3: "291_Investigators_Office.mp3",
    tags: ["detective", "Cthulhu", "vintage", "noir", "private eye", "film noir", "Lovecraft", "mythos"],
    disabled: true,
  },
  song_292: {
    title: "Bleakwater Docks",
    mp3: "292_Bleakwater_Docks.mp3",
    tags: ["Cthulhu", "harbor", "boats", "fishing", "village", "whaling", "mythos", "Lovecraft"],
  },
  song_293: {
    title: "Sanitarium",
    mp3: "293_Sanitarium.mp3",
    tags: ["Cthulhu", "Lovecraft", "mythos", "hospital", "asylum"],
  },
  song_294: {
    title: "Cutpurse Pursuit",
    mp3: "294_Cutpurse_Pursuit.mp3",
    tags: ["medieval", "town", "city", "alley", "urban", "chase", "Witcher"],
  },
  song_295: {
    title: "Closing Time",
    mp3: "295_Closing_Time.mp3",
    tags: ["cyberpunk", "city", "urban", "traffic", "night"],
    disabled: true,
  },
  song_296: {
    title: "The Frozen Trail",
    mp3: "296_The_Frozen_Trail.mp3",
    tags: ["winter", "ice", "arctic", "north", "cold", "freezing", "snow"],
  },
  song_297: {
    title: "Survivors' Bivouac",
    mp3: "297_Survivors_Bivouac.mp3",
    tags: ["camp", "encampment", "campsite", "refugee", "retreat", "sad", "campfire"],
    disabled: true,
  },
  song_298: {
    title: "Gateway to Hell",
    mp3: "298_Gateway_to_Hell.mp3",
    tags: ["volcano", "crater", "fire", "fiery", "evil", "hades", "underworld", "brimstone"],
  },
  song_299: {
    title: "Necropolis",
    mp3: "299_Necropolis.mp3",
    tags: ["ruins", "ancient", "death", "city", "decay", "rubble", "crypt", "grave", "tomb"],
    disabled: true,
  },
  song_300: {
    title: "Burn Maneuver",
    mp3: "300_Burn_Maneuver.mp3",
    tags: ["space", "spaceship", "stars", "star trek", "expanse", "rocket", "starship", "engines"],
  },
  song_301: {
    title: "Pool of Radiance",
    mp3: "301_Pool_of_Radiance.mp3",
    tags: ["water", "magic", "peaceful", "ritual", "temple", "ethereal", "blood", "arcane"],
  },
  song_302: {
    title: "Floating Market",
    mp3: "302_Floating_Market.mp3",
    tags: ["water", "bazaar", "vendor", "river", "inlet", "shop", "wares", "canal"],
    disabled: true,
  },
  song_303: {
    title: "Summoning",
    mp3: "303_Summoning.mp3",
    tags: ["witches", "witchcraft", "coven", "ritual", "seance", "occult", "magic"],
  },
  song_304: {
    title: "Fog of War",
    mp3: "304_Fog_of_War.mp3",
    tags: ["vikings", "battle", "camp", "bivouac", "suspense", "dread", "ominous"],
  },
  song_305: {
    title: "Hidden Valley",
    mp3: "305_Hidden_Valley.mp3",
    tags: ["wind", "quiet", "peaceful", "safe", "verdant", "vale", "trees", "birds"],
    disabled: true,
  },
  song_306: {
    title: "Aftermath",
    mp3: "306_Aftermath.mp3",
    tags: ["nuclear", "cataclysm", "wasteland", "survivor", "dead", "barren"],
    disabled: true,
  },
  song_307: {
    title: "Sand Raiders",
    mp3: "307_Sand_Raiders.mp3",
    tags: ["Star Wars", "Tusken Raiders", "Tatooine", "desert", "battle", "action", "combat"],
  },
  song_308: {
    title: "Skullwharf",
    mp3: "308_Skullwharf.mp3",
    tags: ["port", "docks", "underground", "underdark", "cave", "Skullport", "Waterdeep", "drow"],
    disabled: true,
  },
  song_309: {
    title: "Bloodgate",
    mp3: "309_Bloodgate.mp3",
    tags: ["gateway", "portal", "dimension", "lich", "sword coast", "blood", "wizards"],
    disabled: true,
  },
  song_310: {
    title: "Moisture Farm",
    mp3: "310_Moisture_Farm.mp3",
    tags: ["Star Wars", "Tatooine", "desert", "barren", "water", "Dune"],
    disabled: true,
  },
  song_311: {
    title: "Swamp Thing",
    mp3: "311_Swamp_Thing.mp3",
    tags: ["marsh", "monster", "spooky", "boat", "water", "bog", "creature"],
  },
  song_312: {
    title: "Generation Ship",
    mp3: "312_Generation_Ship.mp3",
    tags: ["space", "interstellar", "mothership", "spaceship", "stars", "expanse", "star trek"],
    disabled: true,
  },
  song_313: {
    title: "Dusk of the Dryad",
    mp3: "313_Dusk_of_the_Dryad.mp3",
    tags: ["woods", "forest", "trees", "spooky", "nymph", "feywild", "fey", "faerie"],
    disabled: true,
  },
  song_314: {
    title: "Shuttle Crash",
    mp3: "314_Shuttle_Crash.mp3",
    tags: ["alien", "planet", "jungle", "swamp", "derelict", "spaceship", "wreck", "shipwreck"],
    disabled: true,
  },
  song_315: {
    title: "Dragon Rider",
    mp3: "315_Dragon_Rider.mp3",
    tags: ["action", "wyvern", "wind", "chase", "battle", "combat", "dragons", "drakes", "pern"],
    disabled: true,
  },
  song_316: {
    title: "Goblin Ambush",
    mp3: "316_Goblin_Ambush.mp3",
    tags: ["battle", "action", "combat", "Phandelver", "chase", "skirmish"],
  },
  song_317: {
    title: "Robot Scrapyard",
    mp3: "317_Robot_Scrapyard.mp3",
    tags: ["cyberpunk", "peaceful", "mech", "android", "machine", "factory", "junkyard"],
    disabled: true,
  },
  song_318: {
    title: "The Gaping Maw",
    mp3: "318_The_Gaping_Maw.mp3",
    tags: ["gate", "mordor", "action", "drama", "battle", "combat", "hell", "tolkien", "passage"],
  },
  song_319: {
    title: "Shaman's Hollow",
    mp3: "319_Shamans_Hollow.mp3",
    tags: ["forest", "woods", "magic", "ritual", "druids", "archdruids", "pagan"],
    disabled: true,
  },
  song_320: {
    title: "Cultist's Cavern",
    mp3: "320_Cultists_Cavern.mp3",
    tags: ["pagan", "ritual", "magic", "occult", "ominous", "chant", "summon"],
    disabled: true,
  },
  song_321: {
    title: "Invisible Mountain",
    mp3: "321_Invisible_Mountain.mp3",
    tags: ["tepui", "peaceful", "stream", "wind", "clouds", "peak", "summit", "water"],
    disabled: true,
  },
  song_322: {
    title: "Distilled: Cooperage",
    mp3: "322_Distilled_Cooperage.mp3",
    tags: ["barrels", "whiskey", "whisky", "workshop", "craft"],
    disabled: true,
  },
  song_323: {
    title: "Distilled: Backwoods",
    mp3: "323_Distilled_Backwoods.mp3",
    tags: ["still", "whisky", "whiskey", "moonshine", "spirits"],
    disabled: true,
  },
  song_324: {
    title: "Distilled: Highlands",
    mp3: "324_Distilled_Highlands.mp3",
    tags: ["peat", "mountains", "hills", "Scotland", "Scottish", "whiskey", "whisky"],
    disabled: true,
  },
  song_325: {
    title: "Distilled: Warehouse",
    mp3: "325_Distilled_Warehouse.mp3",
    tags: ["barrels", "whiskey", "whisky", "storage", "spirits"],
    disabled: true,
  },
  song_326: {
    title: "Distilled: Tranquility",
    mp3: "326_Distilled_Tranquility.mp3",
    tags: ["Asia", "China", "Japan", "Zen", "peaceful", "baijiu", "whiskey", "whisky", "garden"],
    disabled: true,
  },
  song_327: {
    title: "Distilled: Tropical",
    mp3: "327_Distilled_Tropical.mp3",
    tags: ["beach", "ocean", "waves", "surf", "tiki", "rum", "tropics", "whiskey", "whisky"],
    disabled: true,
  },
  song_328: {
    title: "Battle Requiem",
    mp3: "328_Battle_Requiem.mp3",
    tags: ["war", "tragedy", "battlefield", "defeat", "sorrow", "retreat", "refugee"],
  },
  song_329: {
    title: "Desert Temple",
    mp3: "329_Desert_Temple.mp3",
    tags: ["sand", "wasteland", "dune", "Bedouin", "tribal", "desert", "barren"],
  },
  song_330: {
    title: "Mega City Slums",
    mp3: "330_Mega_City_Slums.mp3",
    tags: ["cyberpunk", "urban", "future", "tech", "Blade Runner", "ghetto", "dystopian"],
  },
  song_331: {
    title: "Drowned Sailors",
    mp3: "331_Drowned_Sailors.mp3",
    tags: ["beach", "ocean", "shipwreck", "water", "zombies", "battle", "action"],
  },
  song_332: {
    title: "Myconid Colony",
    mp3: "332_Myconid_Colony.mp3",
    tags: ["underdark", "dank", "dark", "spooky", "moist", "mushroom", "fungus", "magic"],
    disabled: true,
  },
  song_333: {
    title: "Arcane Athenaeum",
    mp3: "333_Arcane_Athenaeum.mp3",
    tags: ["libary", "magic", "books", "scrolls", "scribe", "Candlekeep"],
    disabled: true,
  },
  song_334: {
    title: "Harpies' Nest",
    mp3: "334_Harpies_Nest.mp3",
    tags: ["harpy", "action", "battle", "wind", "wings", "cliff", "mountain", "monster"],
  },
  song_335: {
    title: "Abandoned Chapel",
    mp3: "335_Abandoned_Chapel.mp3",
    tags: ["temple", "church", "cathedral", "ruins", "gothic", "decay"],
  },
  song_336: {
    title: "Medieval Banquet",
    mp3: "336_Medieval_Banquet.mp3",
    tags: ["feast", "party", "gathering", "wedding", "court", "castle", "dinner", "food"],
  },
  song_337: {
    title: "Village of the Damned",
    mp3: "337_Village_of_the_Damned.mp3",
    tags: ["scary", "storm", "rain", "creepy", "halloween", "barovia", "gothic", "town", "supernatural"],
  },
  song_338: {
    title: "Adventure Supply",
    mp3: "338_Adventure_Supply.mp3",
    tags: ["shop", "store", "merchant", "general store", "goods", "supplies"],
    disabled: true,
  },
  song_339: {
    title: "Red Planet",
    mp3: "339_Red_Planet.mp3",
    tags: ["mars", "desert", "wind", "sand", "habitat", "space", "colony", "Dune"],
    disabled: true,
  },
  song_340: {
    title: "Starbase Omega",
    mp3: "340_Starbase_Omega.mp3",
    tags: ["space", "spacestation", "spaceship", "interstellar", "outpost", "space station"],
  },
  song_341: {
    title: "Beggar's Rest",
    mp3: "341_Beggars_Rest.mp3",
    tags: ["city", "village", "slum", "ghetto", "victorian", "flea bottom", "street"],
  },
  song_342: {
    title: "Tavern Celebration",
    mp3: "342_Tavern_Celebration.mp3",
    tags: ["inn", "festival", "dance", "party", "action", "tavern", "happy"],
    disabled: true,
  },
  song_343: {
    title: "Dungeon Collapse",
    mp3: "343_Dungeon_Collapse.mp3",
    tags: ["action", "battle", "combat", "chase", "church", "temple", "ruins", "destruction"],
  },
  song_344: {
    title: "Yōkai Forest",
    mp3: "344_Yokai_Forest.mp3",
    tags: ["yokai", "demon", "spirit", "Japan", "Japanese", "mysterious", "trees"],
  },
  song_345: {
    title: "High Seas Pursuit",
    mp3: "345_High_Seas_Pursuit.mp3",
    tags: ["ship", "ships", "sailing", "ocean", "battle", "action", "chase", "sail"],
  },
  song_346: {
    title: "Tinkertown",
    mp3: "346_Tinkertown.mp3",
    tags: ["robots", "machines", "junkyard", "cyberpunk", "metal", "mechanical", "future", "tech"],
  },
  song_347: {
    title: "Elven Procession",
    mp3: "347_Elven_Procession.mp3",
    tags: ["forest", "woods", "elves", "elf", "tolkien", "spirits", "peaceful"],
  },
  song_348: {
    title: "Viking Village",
    mp3: "348_Viking_Village.mp3",
    tags: ["town", "north", "snow", "cold", "village", "ice", "mountains", "frozen"],
  },
  song_349: {
    title: "Puzzle Dungeon",
    mp3: "349_Puzzle_Dungeon.mp3",
    tags: ["labyrinth", "maze", "mechanical", "crypt", "sneak", "tension"],
    disabled: true,
  },
  song_350: {
    title: "Covert Ops",
    mp3: "350_Covert_Ops.mp3",
    tags: ["spy", "espionage", "city", "urban", "stakeout", "noir", "street"],
  },
  song_351: {
    title: "Halfling Lodge",
    mp3: "351_Halfling_Lodge.mp3",
    tags: ["tavern", "inn", "hobbits", "tolkien", "happy", "festive", "party"],
  },
  song_352: {
    title: "Black Rider",
    mp3: "352_Black_Rider.mp3",
    tags: ["tolkien", "hobbits", "action", "nazgul", "horses", "forest", "chase"],
  },
  song_353: {
    title: "Spirit of the Plains",
    mp3: "353_Spirit_of_the_Plains.mp3",
    tags: ["peaceful", "magical", "magic", "spiritual", "wind", "deer", "stag"],
  },
  song_354: {
    title: "Warlock's Whisper",
    mp3: "354_Warlocks_Whisper.mp3",
    tags: ["magic", "dark", "evil", "sorcery", "creepy", "wizard", "energy"],
  },
  song_355: {
    title: "Hydroponics Bay",
    mp3: "355_Hydroponics_Bay.mp3",
    tags: ["starship", "Star Trek", "Enterprise", "vines", "technology", "botany", "garden"],
  },
  song_356: {
    title: "Adventure Begins",
    mp3: "356_Adventure_Begins.mp3",
    tags: ["Waterdeep", "Neverwinter", "Baldur's Gate", "city", "intro", "beginning"],
  },
  song_357: {
    title: "Promontory",
    mp3: "357_Promontory.mp3",
    tags: ["ocean", "waves", "cliff", "clifftop", "bluff", "overlook", "peaceful"],
    disabled: true,
  },
  song_358: {
    title: "Egg Chamber",
    mp3: "358_Egg_Chamber.mp3",
    tags: ["alien", "aliens", "creepy", "hatchery", "brood"],
    disabled: true,
  },
  song_359: {
    title: "Skull Island",
    mp3: "359_Skull_Island.mp3",
    tags: ["ocean", "adventure", "drama", "ship", "shipwreck", "tribal", "jungle", "King Kong", "Kong"],
  },
  song_360: {
    title: "Pit Fighter",
    mp3: "360_Pit_Fighter.mp3",
    tags: ["arena", "colosseum", "gladiators", "combat", "trial", "duel", "sport", "blood sport"],
  },
  song_361: {
    title: "Ancient Beacon",
    mp3: "361_Ancient_Beacon.mp3",
    tags: ["desert", "dune", "pyramid", "ansible", "sand", "wind", "bedouin", "stargate"],
    disabled: true,
  },
  song_362: {
    title: "Rolling Emporium",
    mp3: "362_Rolling_Emporium.mp3",
    tags: ["oxen", "oxcart", "aurochs", "market", "vendors", "nomads", "wagon", "souk"],
  },
  song_363: {
    title: "Starship Adrift",
    mp3: "363_Starship_Adrift.mp3",
    tags: ["space", "spaceship", "Star Trek", "interstellar", "mothership", "Expanse"],
    disabled: true,
  },
  song_364: {
    title: "River of Blood",
    mp3: "364_River_of_Blood.mp3",
    tags: ["Avernus", "barren", "wasteland", "dead", "hell", "hades"],
    disabled: true,
  },
  song_365: {
    title: "Trail of Ashes",
    mp3: "365_Trail_of_Ashes.mp3",
    tags: ["war", "marching", "march", "battlefield", "celtic", "medieval", "armor", "army"],
  },
  song_366: {
    title: "Roc's Nest",
    mp3: "366_Rocs_Nest.mp3",
    tags: ["mountain", "clifftop", "birds", "tension", "drama", "wings", "monster"],
  },
  song_367: {
    title: "Rope Bridge",
    mp3: "367_Rope_Bridge.mp3",
    tags: ["jungle", "clifftop", "cliff", "danger", "suspense", "swing bridge"],
    disabled: true,
  },
  song_368: {
    title: "Ghosts of Appalachia",
    mp3: "368_Ghosts_of_Appalachia.mp3",
    tags: ["hut", "shack", "spirits", "country", "cottage", "abandoned", "forest", "winter", "cabin", "house"],
    disabled: true,
  },
  song_369: {
    title: "Troll Grotto",
    mp3: "369_Troll_Grotto.mp3",
    tags: ["cave", "monster", "tribal", "tense", "giant", "Scandinavian", "Norse", "Nordic"],
  },
  song_370: {
    title: "Awakenings",
    mp3: "370_Awakenings.mp3",
    tags: ["robot", "android", "artificial", "automaton", "computers", "laboratory", "cyberpunk"],
  },
  song_371: {
    title: "Whirlpool",
    mp3: "371_Whirlpool.mp3",
    tags: ["shipwreck", "ship", "ocean", "sea", "waves", "Poseidon", "action", "sail", "sailing"],
  },
  song_372: {
    title: "Den of Iniquity",
    mp3: "372_Den_of_Iniquity.mp3",
    tags: ["tavern", "bar", "pub", "brothel", "inn", "alehouse"],
  },
  song_373: {
    title: "Infernal Machine",
    mp3: "373_Infernal_Machine.mp3",
    tags: ["mechanical", "mechanism", "steampunk", "clockwork", "steam", "gears", "engines"],
  },
  song_374: {
    title: "Hall of Angels",
    mp3: "374_Hall_of_Angels.mp3",
    tags: ["museum", "sculpture", "statues", "seraphs", "archons", "gallery"],
  },
  song_375: {
    title: "Rise of the Golem",
    mp3: "375_Rise_of_the_Golem.mp3",
    tags: ["magic", "spells", "wizards", "clay", "construct", "incantation", "cleric"],
  },
  song_376: {
    title: "Voyage Begins",
    mp3: "376_Voyage_Begins.mp3",
    tags: ["docks", "intro", "beginning", "ships", "sailing", "adventure", "pier", "journey", "travel"],
  },
  song_377: {
    title: "Through the Woods",
    mp3: "377_Through_the_Woods.mp3",
    tags: ["horses", "carriage", "buggy", "chase", "action", "battle", "tension", "forest"],
  },
  song_378: {
    title: "Descent",
    mp3: "378_Descent.mp3",
    tags: ["cave", "cavern", "underdark", "underground", "drow", "mine", "pit", "rope"],
  },
  song_379: {
    title: "Terraforming",
    mp3: "379_Terraforming.mp3",
    tags: ["Mars", "Terraforming Mars", "atmosphere", "machine", "factory", "industrial", "planet"],
    disabled: true,
  },
  song_380: {
    title: "The Great Lift",
    mp3: "380_The_Great_Lift.mp3",
    tags: ["machine", "mechanical", "steampunk", "engine", "gears", "clifftop", "elevator", "mountain"],
  },
  song_381: {
    title: "Halfling Sneak",
    mp3: "381_Halfling_Sneak.mp3",
    tags: ["stealth", "comedy", "hobbits", "castle", "escape", "guards", "heist"],
  },
  song_382: {
    title: "Long Rest",
    mp3: "382_Long_Rest.mp3",
    tags: ["camp", "campsite", "quiet", "peaceful", "forest", "night", "campfire"],
    disabled: true,
  },
  song_383: {
    title: "Banshee's Lair",
    mp3: "383_Banshees_Lair.mp3",
    tags: ["house", "shack", "cabin", "witch", "crone", "cottage"],
    disabled: true,
  },
  song_384: {
    title: "Western Watchtower",
    mp3: "384_Western_Watchtower.mp3",
    tags: ["fortress", "ruins", "mountains", "castle", "fort", "outpost", "guard tower", "tower"],
  },
  song_385: {
    title: "Infiltration",
    mp3: "385_Infiltration.mp3",
    tags: ["stealth", "escape", "heist", "guards", "facility", "spy", "sneak"],
    disabled: true,
  },
  song_386: {
    title: "The Attic",
    mp3: "386_The_Attic.mp3",
    tags: ["house", "haunted", "creepy", "scary", "ghosts", "spirits", "hut", "shack", "halloween"],
  },
  song_387: {
    title: "Docking Bay",
    mp3: "387_Docking_Bay.mp3",
    tags: ["mechs", "army", "troops", "battle", "action", "chase", "hangar", "spaceship", "droids"],
  },
  song_388: {
    title: "Lord of Bones",
    mp3: "388_Lord_of_Bones.mp3",
    tags: ["monster", "skeleton", "dungeon", "hell", "boss", "action", "fire", "battle"],
  },
  song_389: {
    title: "Medieval Market",
    mp3: "389_Medieval_Market.mp3",
    tags: ["peaceful", "spring", "birds", "town", "city", "square", "magic", "happy", "festival"],
  },
  song_390: {
    title: "Desert Devotional",
    mp3: "390_Desert_Devotional.mp3",
    tags: ["temple", "monks", "chant", "prayer", "Dune", "Arrakis", "sand", "peaceful", "quiet"],
    disabled: true,
  },
  song_391: {
    title: "Train Job",
    mp3: "391_Train_Job.mp3",
    tags: ["action", "suspense", "chase", "locomotive", "steam", "spy", "tension", "heist", "Bond"],
  },
  song_392: {
    title: "Trireme",
    mp3: "392_Trireme.mp3",
    tags: ["ocean", "sea", "waves", "boat", "ship", "sailing", "greece", "greek", "islands", "sparta"],
  },
  song_393: {
    title: "Hellhound Alley",
    mp3: "393_Hellhound_Alley.mp3",
    tags: ["cyberpunk", "street", "night", "dogs", "gritty", "urban", "desolate"],
  },
  song_394: {
    title: "Demon Army",
    mp3: "394_Demon_Army.mp3",
    tags: ["battle", "action", "war", "underworld", "devil", "fight", "blood wars", "lava", "fire"],
  },
  song_395: {
    title: "Launch Day",
    mp3: "395_Launch_Day.mp3",
    tags: ["cyberpunk", "spacehip", "spacestation", "space", "rocket", "gantry", "exploration", "Star Trek", "space station"],
    disabled: true,
  },
  song_396: {
    title: "The Ansible",
    mp3: "396_The_Ansible.mp3",
    tags: ["artifact", "ruins", "ancient", "mountain", "beacon", "communication", "ultrawave"],
  },
  song_397: {
    title: "Homecoming",
    mp3: "397_Homecoming.mp3",
    tags: ["medieval", "festival", "city", "town", "celebration", "uplifting", "heroic", "vicotory", "fanfare"],
  },
  song_398: {
    title: "The Misty Marsh",
    mp3: "398_The_Misty_Marsh.mp3",
    tags: ["ocean", "sea", "water", "Saltmarsh", "peaceful", "breeze", "birds", "reeds", "boat", "wetlands"],
  },
  song_399: {
    title: "Whiteout",
    mp3: "399_Whiteout.mp3",
    tags: ["winter", "snow", "blizzard", "tundra", "arctic", "ice", "Icewind", "wind", "frozen", "storm"],
  },
  song_400: {
    title: "Whispering Caverns",
    mp3: "400_Whispering_Caverns.mp3",
    tags: ["cave", "grotto", "spirits", "ghosts", "underdark", "mine", "underground", "tomb"],
  },
  song_401: {
    title: "Feast of Crispian",
    mp3: "401_Feast_of_Crispian.mp3",
    tags: ["tavern", "inn", "pub", "hall", "bard", "celebration", "festival", "party"],
  },
  song_402: {
    title: "The Drowned Tower",
    mp3: "402_The_Drowned_Tower.mp3",
    tags: ["underwater", "ocean", "sea", "ruins", "dive", "whales", "water", "depths", "sunken pyramid"],
  },
  song_403: {
    title: "Steel Foundry",
    mp3: "403_Steel_Foundry.mp3",
    tags: ["dwarven", "dwarf", "metal", "blacksmith", "factory", "moria", "hammer", "smelt"],
  },
  song_404: {
    title: "Vampyr",
    mp3: "404_Vampyr.mp3",
    tags: ["castle", "undead", "vampire", "Strahd", "Ravenloft", "Dracula", "Barovia"],
    disabled: true,
  },
  song_405: {
    title: "Brood Mother",
    mp3: "405_Brood_Mother.mp3",
    tags: ["spiders", "hatchery", "aragog", "aliens", "cave", "lair", "hive", "dungeon", "boss"],
  },
  song_406: {
    title: "Treacherous Path",
    mp3: "406_Treacherous_Path.mp3",
    tags: ["danger", "road", "lava", "fire", "hell", "mordor", "demons", "underworld", "bridge"],
  },
  song_407: {
    title: "Viking Tavern",
    mp3: "407_Viking_Tavern.mp3",
    tags: ["inn", "bar", "pub", "alehouse", "warm", "fireplace", "longhouse", "tavern"],
  },
  song_408: {
    title: "Nautiloid Escape",
    mp3: "408_Nautiloid_Escape.mp3",
    tags: ["Mind Flayers", "ilithid", "elder brain", "action", "suspense", "crash", "shipwreck"],
  },
  song_409: {
    title: "Docking Procedure",
    mp3: "409_Docking_Procedure.mp3",
    tags: ["space", "spaceship", "spacestation", "freight", "cargo", "rendezvous", "port", "starship", "space station"],
    disabled: true,
  },
  song_410: {
    title: "Forgotten Forest",
    mp3: "410_Forgotten_Forest.mp3",
    tags: ["woods", "dark", "magic", "magical", "spooky", "druids", "exploration"],
  },
  song_411: {
    title: "Ship of the Line",
    mp3: "411_Ship_of_the_Line.mp3",
    tags: ["ocean", "sea", "waves", "sailing", "sailboat", "wind", "nautical", "navy", "naval"],
  },
  song_412: {
    title: "Tomb Guardians",
    mp3: "412_Tomb_Guardians.mp3",
    tags: ["statues", "crypt", "cave", "cavern", "underground", "automaton", "monster"],
  },
  song_413: {
    title: "Collegium Magica",
    mp3: "413_Collegium_Magica.mp3",
    tags: ["library", "study", "mage", "maester", "research", "symposium", "books", "scrolls"],
  },
  song_414: {
    title: "Stakeout",
    mp3: "414_Stakeout.mp3",
    tags: ["city", "urban", "spy", "spies", "cyberpunk", "technology", "surveillance", "camera"],
  },
  song_415: {
    title: "Jungle Bunker",
    mp3: "415_Jungle_Bunker.mp3",
    tags: ["forest", "Endor", "Star Wars", "Stormtroopers", "redoubt", "action", "mechs", "at-st"],
  },
  song_416: {
    title: "Rebuilding",
    mp3: "416_Rebuilding.mp3",
    tags: ["city", "village", "town", "medieval", "construction", "repair", "square"],
  },
  song_417: {
    title: "Mainframe",
    mp3: "417_Mainframe.mp3",
    tags: ["motherboard", "computer", "cyberpunk", "cyberspace", "metaverse", "Tron", "Shodan", "Glados"],
    disabled: true,
  },
  song_418: {
    title: "Pagan Woods",
    mp3: "418_Pagan_Woods.mp3",
    tags: ["forest", "ruins", "norse", "viking", "druids", "witches", "ritual", "magic", "spirits"],
  },
  song_419: {
    title: "Hidden Passage",
    mp3: "419_Hidden_Passage.mp3",
    tags: ["tunnel", "mountain pass", "shortcut", "cave", "cavern", "road", "action", "path"],
    disabled: true,
  },
  song_420: {
    title: "Counting House",
    mp3: "420_Counting_House.mp3",
    tags: ["bank", "money", "exchange", "Gringotts", "trade", "currency"],
  },
  song_421: {
    title: "The Madding Crowd",
    mp3: "421_The_Madding_Crowd.mp3",
    tags: ["city", "urban", "town", "Waterdeep", "Baldur's Gate", "medieval", "market"],
  },
  song_422: {
    title: "Ghost Ship",
    mp3: "422_Ghost_Ship.mp3",
    tags: ["boat", "ship", "sailing", "water", "ocean", "sea", "pirates", "navy", "nautical"],
  },
  song_423: {
    title: "Magical Flora",
    mp3: "423_Magical_Flora.mp3",
    tags: ["biome", "forest", "flowers", "jungle", "alien", "planet", "peaceful", "pandora"],
  },
  song_424: {
    title: "Frontier Town",
    mp3: "424_Frontier_Town.mp3",
    tags: ["west", "American", "cowboys", "village", "horses", "outpost", "western", "Deadlands"],
  },
  song_425: {
    title: "The Stranger",
    mp3: "425_The_Stranger.mp3",
    tags: ["west", "American", "cowboys", "horses", "Deadlands", "dark", "haunted", "mysterious", "western"],
    disabled: true,
  },
  song_426: {
    title: "Stagecoach Heist",
    mp3: "426_Stagecoach_Heist.mp3",
    tags: ["west", "American", "cowboys", "horses", "action", "chase", "Deadlands", "gunfire", "battle", "western"],
  },
  song_427: {
    title: "Bug Hunt",
    mp3: "427_Bug_Hunt.mp3",
    tags: ["alien", "aliens", "spacestation", "spaceship", "action", "nostromo", "xenomorph", "space station"],
  },
  song_428: {
    title: "The Sisterhood",
    mp3: "428_The_Sisterhood.mp3",
    tags: ["Dune", "Arrakis", "Bene Geserit", "Chapterhouse", "coven", "temple", "prayer"],
  },
  song_429: {
    title: "Imperial Pursuit",
    mp3: "429_Imperial_Pursuit.mp3",
    tags: ["Star Wars", "Deathstar", "Stormtroopers", "Empire", "spacestation", "chase", "space station"],
  },
  song_430: {
    title: "Fire Dance",
    mp3: "430_Fire_Dance.mp3",
    tags: ["pagan", "ritual", "jungle", "forest", "tribal", "drums", "chant"],
  },
  song_431: {
    title: "Hotel Noir",
    mp3: "431_Hotel_Noir.mp3",
    tags: ["1940s", "1930s", "Cthulhu", "jazz", "city", "detective", "mystery", "spy", "espionage"],
  },
  song_432: {
    title: "Lair of the Wyrm",
    mp3: "432_Lair_of_the_Wyrm.mp3",
    tags: ["cave", "cavern", "dragon", "boss", "dungeon", "action", "monster"],
  },
  song_433: {
    title: "Spectral Abbey",
    mp3: "433_Spectral_Abbey.mp3",
    tags: ["castle", "ruins", "clifftop", "wind", "cliffs", "ghosts", "spirits", "magic", "monastery"],
  },
  song_434: {
    title: "Cryo Pods",
    mp3: "434_Cryo_Pods.mp3",
    tags: ["spaceship", "alien", "aliens", "isolation", "stasis", "space", "interstellar"],
    disabled: true,
  },
  song_435: {
    title: "The Undercroft",
    mp3: "435_The_Undercroft.mp3",
    tags: ["castle", "cellar", "basement", "dungeon", "underground", "secrets", "passage"],
  },
  song_436: {
    title: "Winter Encampment",
    mp3: "436_Winter_Encampment.mp3",
    tags: ["camp", "bivouac", "army", "soldiers", "woods", "snow", "medieval", "campsite"],
  },
  song_437: {
    title: "Dungeon Asylum",
    mp3: "437_Dungeon_Asylum.mp3",
    tags: ["sanitarium", "demons", "prison", "underground", "monsters", "jail"],
  },
  song_438: {
    title: "Red Sky Mine",
    mp3: "438_Red_Sky_Mine.mp3",
    tags: ["excavation", "dig", "alien", "aliens", "mining", "machinery", "trucks"],
  },
  song_439: {
    title: "Goodhaven",
    mp3: "439_Goodhaven.mp3",
    tags: ["town", "village", "river", "lake", "peaceful", "welcome", "rest"],
  },
  song_440: {
    title: "Map Chamber",
    mp3: "440_Map_Chamber.mp3",
    tags: ["peaceful", "Greek", "Roman", "water", "pool", "magic", "magical", "desert"],
  },
  song_441: {
    title: "Tech Market",
    mp3: "441_Tech_Market.mp3",
    tags: ["cyberpunk", "urban", "city", "noire", "night", "vendors", "technology"],
  },
  song_442: {
    title: "Darkmoor",
    mp3: "442_Darkmoor.mp3",
    tags: ["werewolf", "monster", "woods", "moors", "night", "country", "action"],
  },
  song_443: {
    title: "Primate Lab",
    mp3: "443_Primate_Lab.mp3",
    tags: ["science", "laboratory", "animals", "experiments", "monkeys", "apes", "cages"],
  },
  song_444: {
    title: "Yultide Cantrips",
    mp3: "444_Yuletide_Cantrips.mp3",
    tags: ["city", "Neverwinter", "Baldur's Gate", "fireworks", "celebration", "Christmas", "festival"],
  },
  song_445: {
    title: "Lava King's Lair",
    mp3: "445_Lava_Kings_Lair.mp3",
    tags: ["cave", "cavern", "grotto", "lava", "boss", "underground", "fire", "magma"],
    disabled: true,
  },
  song_446: {
    title: "Between Adventures",
    mp3: "446_Between_Adventures.mp3",
    tags: ["tavern", "inn", "downtime", "peaceful", "rest", "fireplace", "hearth"],
  },
  song_447: {
    title: "The Murky Depths",
    mp3: "447_The_Murky_Depths.mp3",
    tags: ["underground", "underdark", "cavern", "jungle", "forest", "verdant"],
  },
  song_448: {
    title: "Checkpoint Omega",
    mp3: "448_Checkpoint_Omega.mp3",
    tags: ["soldiers", "military", "space station", "spacestation", "facility", "guards", "gate", "security"],
  },
  song_449: {
    title: "A Royal Visit",
    mp3: "449_A_Royal_Visit.mp3",
    tags: ["medieval", "procession", "festival", "parade", "city", "Neverwinter", "Baldur's Gate", "celebration"],
  },
  song_450: {
    title: "Nightlands",
    mp3: "450_Nightlands.mp3",
    tags: ["shadows", "barren", "wasteland", "darkness", "ruined", "magic", "underdark"],
  },
  song_451: {
    title: "Orb of Doom",
    mp3: "451_Orb_of_Doom.mp3",
    tags: ["magic", "monks", "chant", "magical", "energy", "chamber", "sphere"],
  },
  song_452: {
    title: "The Last Express",
    mp3: "452_The_Last_Express.mp3",
    tags: ["trains", "steam", "train station", "station", "action", "noir", "escape"],
    disabled: true,
  },
  song_453: {
    title: "Capes and Canes",
    mp3: "453_Capes_and_Canes.mp3",
    tags: ["London", "city", "victorian", "rain", "fog", "horses", "streets", "carriage", "sneak"],
  },
  song_454: {
    title: "Broken Pantheon",
    mp3: "454_Broken_Pantheon.mp3",
    tags: ["temple", "dungeon", "spirits", "ruins", "church", "sanctuary", "church"],
  },
  song_455: {
    title: "Harper's Waypoint",
    mp3: "455_Harpers_Waypoint.mp3",
    tags: ["tavern", "inn", "woods", "evening", "harp", "secret", "forest"],
  },
  song_456: {
    title: "Drawing Room: Night",
    mp3: "456_Drawing_Room_Night.mp3",
    tags: ["victorian", "parlor", "storm", "night", "mansion", "manor", "downton"],
  },
  song_457: {
    title: "Hunting Grounds",
    mp3: "457_Hunting_Grounds.mp3",
    tags: ["dragons", "dragon", "drakes", "mountains", "fields", "wind", "hunt"],
  },
  song_458: {
    title: "Deep Blue",
    mp3: "458_Deep_Blue.mp3",
    tags: ["ocean", "sea", "underwater", "kelp", "whales", "Aquasphere", "depths", "submarine"],
  },
  song_459: {
    title: "Xenon Refinery",
    mp3: "459_Xenon_Refinery.mp3",
    tags: ["planet", "space", "outpost", "alien", "machinery", "terraforming", "mining", "barren"],
  },
  song_460: {
    title: "Doll Shoppe",
    mp3: "460_Doll_Shoppe.mp3",
    tags: ["manequins", "creepy", "Victorian", "shop", "ghosts", "haunted", "magic", "porcelain", "poppet", "bisque"],
  },
  song_461: {
    title: "Resurrection",
    mp3: "461_Resurrection.mp3",
    tags: ["ice", "snow", "mammoth", "wizards", "magic", "cleric", "frozen"],
  },
  song_462: {
    title: "Foghaven",
    mp3: "462_Foghaven.mp3",
    tags: ["town", "village", "city", "medieval", "rain", "mist", "streets", "industrial"],
  },
  song_463: {
    title: "Listening Post",
    mp3: "463_Listening_Post.mp3",
    tags: ["acrtic", "antarctica", "hoth", "space", "spacestation", "nostromo", "outpost", "radio", "The Thing"],
  },
  song_464: {
    title: "Petrified Forest",
    mp3: "464_Petrified_Forest.mp3",
    tags: ["woods", "medusa", "gorgon", "basilisk", "temple", "ruins", "stone", "magic", "barren"],
  },
  song_465: {
    title: "Light the Beacons",
    mp3: "465_Light_the_Beacons.mp3",
    tags: ["army", "battle", "fight", "skirmish", "war", "siege", "combat", "action"],
  },
  song_466: {
    title: "Drow Slave Camp",
    mp3: "466_Drow_Slave_Camp.mp3",
    tags: ["underground", "underdark", "prison", "jail", "labor", "work", "cave", "cages", "whips"],
  },
  song_467: {
    title: "Battle Stations",
    mp3: "467_Battle_Stations.mp3",
    tags: ["war", "machines", "deck", "hangar", "mechs", "space", "spaceship", "spacestation", "crew"],
  },
  song_468: {
    title: "Steampunk Telescope",
    mp3: "468_Steampunk_Telescope.mp3",
    tags: ["Eberron", "observatory", "mechanical", "machinery", "astronomy", "space", "machines"],
  },
  song_469: {
    title: "Monsoon Temple",
    mp3: "469_Monsoon_Temple.mp3",
    tags: ["asian", "buddhist", "monks", "forest", "rain", "peaceful", "meditate", "prayer"],
  },
  song_470: {
    title: "The Threshing Hour",
    mp3: "470_The_Threshing_Hour.mp3",
    tags: ["cornfield", "windmill", "farm", "rural", "field", "desolate", "rust", "mech", "robot"],
  },
};
